### Numpy continuation:

### Iterating of Arrays:

In [2]:
### iterating of lists:

a = [1,2,3,4]

for i in a:   ### 
    print(i,end = " ")

1 2 3 4 

In [4]:
for i in range(len(a)):
    print(a[i],end = " ")
    

1 2 3 4 

In [6]:
### 1-d array iteration:
import numpy as np
a = np.array([1,2,3,4,5,7,8,10,2])

In [7]:
a

array([ 1,  2,  3,  4,  5,  7,  8, 10,  2])

In [9]:
for i in a:
    print(i,end = " ")
    

1 2 3 4 5 7 8 10 2 

In [10]:
### 2-d array:

b = a.reshape(3,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  7],
       [ 8, 10,  2]])

In [12]:
for i in b: ### i holds one row for each iteration
    for j in i:  ### j holds each element from the row.
        print(j,end = " ")

1 2 3 4 5 7 8 10 2 

In [16]:
### 3-d array:

c = a.reshape(3,3,1)
c

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 7]],

       [[ 8],
        [10],
        [ 2]]])

In [17]:
for i in c:
    for j in i:
        for z in j:
            print(z,end= " ")

1 2 3 4 5 7 8 10 2 

In [19]:
### keyword  for iterating the array using numpy:

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 5 7 8 10 2 

In [22]:
for j in np.nditer(b):
    print(j,end = " ")

1 2 3 4 5 7 8 10 2 

### Joining of arrays:



In [36]:
### 1-d array:

a = np.arange(1,10,2)
b = np.arange(10,20,2)
c = np.concatenate((a,b))
c

array([ 1,  3,  5,  7,  9, 10, 12, 14, 16, 18])

In [34]:
### 2-d array:

a = a.reshape(5,1)
b = b.reshape(5,1)

c = np.concatenate((a,b))


In [35]:
c

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [37]:
### 3-d array:

a = a.reshape(5,1,1)
b = b.reshape(5,1,1)
c = np.concatenate((a,b))
c


array([[[ 1]],

       [[ 3]],

       [[ 5]],

       [[ 7]],

       [[ 9]],

       [[10]],

       [[12]],

       [[14]],

       [[16]],

       [[18]]])

In [39]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a = np.array([[1,2,3,4],[1,2,3,4]])
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [46]:
a.ndim

2

### Stastical and Math Operations on arrays:



In [47]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [48]:
np.min(a)  ### minimum value in array

1

In [49]:
np.max(a) ### maximum value in array

4

In [50]:
np.argmax(a) ### maximum value's index

3

In [51]:
np.argmin(a) ### minimum value's index

0

In [52]:
np.mean(a)   ### mean

2.5

In [53]:
np.average(a)  ### average

2.5

In [54]:
np.var(a)  ### variance

1.25

In [55]:
np.median(a) ### median

2.5

In [56]:
np.std(a)  ### standard deviation

1.118033988749895

In [57]:
np.average(a,0)  ### 0 --- column wise

array([1., 2., 3., 4.])

In [59]:
np.average(a,1) ### 1- row wise

array([2.5, 2.5])

In [60]:
np.vstack(a) 

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [61]:
b = np.array([[1,2,3,4],[1,2,3,4]])

In [62]:
np.vstack((a,b))   ### vertical stacking

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [64]:
np.hstack(a) ### horizantal stacking.

array([1, 2, 3, 4, 1, 2, 3, 4])

In [65]:
np.hstack((a,b))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4]])

In [66]:
a

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [67]:
np.sum(a) ### sum 

20

In [68]:
np.sum(a,1)

array([10, 10])

In [69]:
np.sum(a,0)  

array([2, 4, 6, 8])

In [70]:
np.sqrt(a)   ### square root

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [71]:
np.exp(a)   ### exponential 

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

In [72]:
 np.sin(a) ## sin value

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ]])

In [73]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.54030231, -0.41614684, -0.9899925 , -0.65364362]])

In [74]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128],
       [ 1.55740772, -2.18503986, -0.14254654,  1.15782128]])

In [78]:
np.log(a)  ##logaritham

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [0.        , 0.69314718, 1.09861229, 1.38629436]])

In [79]:
np.log2(a)

array([[0.       , 1.       , 1.5849625, 2.       ],
       [0.       , 1.       , 1.5849625, 2.       ]])

In [80]:
np.remainder(a,2)

array([[1, 0, 1, 0],
       [1, 0, 1, 0]], dtype=int32)

In [81]:
np.degrees(a)

array([[ 57.29577951, 114.59155903, 171.88733854, 229.18311805],
       [ 57.29577951, 114.59155903, 171.88733854, 229.18311805]])

In [83]:
np.diff(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [86]:
np.ediff1d(a)  ### consecutive elements diff after converting into 1d array.

array([ 1,  1,  1, -3,  1,  1,  1])

In [95]:
np.i0(a)  ## bessel function

array([[ 1,  2,  4, 11],
       [ 1,  2,  4, 11]])

In [98]:
np.mod(a,1)  ### modulous


array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [99]:
np.power(a,2)   ### power

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16]], dtype=int32)

In [100]:
np.reciprocal(a)  ### reciprocal

array([[1, 0, 0, 0],
       [1, 0, 0, 0]], dtype=int32)

In [102]:
np.multiply(a,2)  ### mutliplication

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [103]:
np.divide(a,2)  ### division 

array([[0.5, 1. , 1.5, 2. ],
       [0.5, 1. , 1.5, 2. ]])

In [105]:
np.floor_divide(a,2)  ### floor division

array([[0, 1, 1, 2],
       [0, 1, 1, 2]], dtype=int32)

In [107]:
np.real(a)    ### real

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [109]:
np.imag(a)    ### imaginary

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### Ravel and Flatten:

* Ravel : If you create a new array using ravel function and made changes in that new array .the changes will be applied to the original array also.

* Flatten : If you create a new array using flatten and made changes in the new array.those changes won't apply to the original array.

In [111]:
a = np.array([1,2,3,4,5])
b = a.ravel()

In [112]:
a  ### original array

array([1, 2, 3, 4, 5])

In [113]:
b   ### new array

array([1, 2, 3, 4, 5])

In [114]:
b[0] = 10

In [115]:
b

array([10,  2,  3,  4,  5])

In [116]:
a

array([10,  2,  3,  4,  5])

In [117]:
a  ### original array

array([10,  2,  3,  4,  5])

In [120]:
b = a.flatten()   ### new array
b

array([10,  2,  3,  4,  5])

In [122]:
b[0] = 1

In [123]:
b

array([1, 2, 3, 4, 5])

In [124]:
a

array([10,  2,  3,  4,  5])

### Random methods:

In [136]:
a = np.random.randint(100)   ### integer value randomly
a

29

In [142]:
np.random.rand()  ### float value in between 0 and 1

0.7213712679596023

In [144]:
np.random.randint(100,size = (5))  ### 1-d array with integer values

array([86, 36, 95, 41, 85])

In [145]:
np.random.randint(100,size = (3,5))  ### 2-d array

array([[82, 25, 64,  1, 94],
       [27, 11, 27, 27, 56],
       [18, 67, 75, 52, 22]])

In [151]:
np.random.rand(3,5)   ## float 2-d array

array([[0.95795642, 0.62976192, 0.55143096, 0.20145596, 0.07819444],
       [0.37523359, 0.84540005, 0.55786991, 0.39394048, 0.67726391],
       [0.65477928, 0.00193066, 0.90337332, 0.62773596, 0.98195714]])

In [159]:
np.random.choice([3,5,6,10])


5

In [160]:
np.random.choice([3,5,6,7,10],size = (3,3))

array([[ 7,  5,  5],
       [10,  6,  6],
       [ 3,  7,  3]])

In [164]:
np.random.choice([3,5,6,7,10],p = [0.1,0.3,0.3,0.1,0.2],size = (3,3))

array([[ 5,  6,  6],
       [ 6, 10,  5],
       [ 6,  5,  6]])

In [175]:
a = np.array([1,2,3,4])
np.random.shuffle(a)   ### values will be shuffled  
a

array([1, 2, 3, 4])

In [177]:
np.random.normal(100,size = (5))

array([ 98.68669898, 101.02217127, 102.62062949, 100.82860844,
       100.5248232 ])

In [180]:
np.random.randn(10) ## combination of positive and negative values

array([-0.92983791, -1.4623614 , -1.04981146,  0.96796046, -1.12505352,
       -0.61459868,  1.87928039, -0.33911469, -0.15048944, -0.04430342])

In [185]:
np.random.binomial(10,p = [0.1],size = (5))  ### binomial distrubution

array([0, 1, 0, 0, 2])

In [191]:
a

array([1, 2, 3, 4])

### Array Filtering:

In [196]:
a = np.array([42,30,22,14])
b = [True,False,True,True] 
c = a[b]
c

array([42, 22, 14])

In [197]:
### print the values greater than 22 in our a array:
b = []
for i in a:
    if i > 22:
        b.append(True)
    else:
        b.append(False)
c = a[b]
c
    

array([42, 30])

In [199]:
d = a > 22
e = a[d]
e

array([42, 30])