### Numpy:

In [1]:
### Installing the library.

In [2]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [3]:
### importing numpy:

import numpy as np

### Creating the arrays:

In [5]:
#### 1-d array:

a = np.array([1,2,34,5])
a

array([ 1,  2, 34,  5])

In [6]:
a.dtype

dtype('int32')

In [7]:
a = np.array(['a','b',3,4])
a

array(['a', 'b', '3', '4'], dtype='<U1')

In [8]:
a.dtype ## checking the data type of array.

dtype('<U1')

In [9]:
a = np.append(a,5)  ### adding new elements to the array.
a

array(['a', 'b', '3', '4', '5'], dtype='<U11')

In [10]:
a = np.arange(0,10) ### creating a range of elements into array.
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a = np.arange(0,10,2)  ### a range of values with step.
a

array([0, 2, 4, 6, 8])

In [13]:
a.nbytes  ## checking the memeory occupied by the array.

20

In [15]:
a.itemsize  ### checking size of each element in array.


4

In [17]:
len(a)  ### number of elements in the array.

5

In [19]:
np.linspace(1,10,20) ### creates array within given range with defined length and there will be equal 
                    ## difference for each neighbour value.

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [21]:
np.logspace(2,5,4)  ### logarithm values with in the defined length with defined base value.

array([   100.,   1000.,  10000., 100000.])

In [28]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [33]:
np.full(10,"python") ### repeats the given string with defined number of times.

array(['python', 'python', 'python', 'python', 'python', 'python',
       'python', 'python', 'python', 'python'], dtype='<U6')

In [49]:
np.full(10,2,dtype = "float")

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [35]:
np.full(10,"1,2")

array(['1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2',
       '1,2'], dtype='<U3')

In [44]:
np.ones(10,dtype = int) ### 1's to be repeated for defined number of times.


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.full(2,10,dtype = "complex")

array([10.+0.j, 10.+0.j])

In [58]:
np.full(2,1+10j)

array([1.+10.j, 1.+10.j])

In [59]:
### 2-d array:   Combination of more 1-d arrays.

### np.array([[list1],[list2],....])

b = np.array([[1,2,3,4],[6,7,8,9],[10,12,2,5]])
b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 12,  2,  5]])

In [62]:
b.ndim   #### checking the dimension of the array.

2

In [61]:
a.ndim

1

In [64]:
b.shape  ### getting the shape of the array.


(3, 4)

In [65]:
b.nbytes

48

In [66]:
b.itemsize

4

In [68]:
len(b)  ### number of rows in array

3

In [69]:
### 3-d array:  combination of two dimensional arrays.

c = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,7,8,9]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 7, 8, 9]]])

In [70]:
len(c) ### number of 2d arrays present

2

In [72]:
c.shape   ## n_of_2-d arrays,n_of_rows,n_of_columns

(2, 2, 4)

In [73]:
c.nbytes

64

In [74]:
c.itemsize

4

In [75]:
c.ndim

3

In [76]:
### Mutli dimensional arrays:

d = np.array([1,2,3,4],ndmin = 5)
d

array([[[[[1, 2, 3, 4]]]]])

In [77]:
d.ndim

5

### Accessing the elements from the array:


In [78]:
### 1-d array:

a

array([0, 2, 4, 6, 8])

In [79]:
a[2]

4

In [80]:
a[2:4]

array([4, 6])

In [81]:
a[-1]

8

In [82]:
a[2:]

array([4, 6, 8])

In [83]:
### 2-d array:
b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 12,  2,  5]])

In [91]:
b[0]   ## row_index

array([1, 2, 3, 4])

In [85]:
b[-1]

array([10, 12,  2,  5])

In [86]:
b[1:]

array([[ 6,  7,  8,  9],
       [10, 12,  2,  5]])

In [88]:
b[0,-1]   ### row_index,element_index

4

In [89]:
b[-1,2]

2

In [92]:
b[:,-1]

array([4, 9, 5])

In [93]:
b[:,2:]

array([[3, 4],
       [8, 9],
       [2, 5]])

In [94]:
b[1:,2:]

array([[8, 9],
       [2, 5]])

In [100]:
b[0::2,1:3]


array([[ 2,  3],
       [12,  2]])

In [99]:
b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 12,  2,  5]])

In [102]:
#### 3-d array:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 7, 8, 9]]])

In [104]:
c[1]

array([[1, 2, 3, 4],
       [5, 7, 8, 9]])

In [106]:
c[0,0]

array([1, 2, 3, 4])

In [107]:
c[0,0,2]

3

In [108]:
c[:,:,2:]

array([[[3, 4],
        [7, 8]],

       [[3, 4],
        [8, 9]]])

In [111]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 7, 8, 9]]])

In [112]:
c[:,0,:2]

array([[1, 2],
       [1, 2]])

In [114]:
c[:,1,2:]

array([[7, 8],
       [8, 9]])

In [115]:
a = np.append(a,[12,3,4])
a

array([ 0,  2,  4,  6,  8, 12,  3,  4])

### Shape of arrays:

In [118]:
### 1-d  array:

a.shape ### number of elements /columns 

(8,)

In [121]:
### 2-d array:

b.shape ### no_of rows,no of columns

(3, 4)

In [123]:
### 3-d array:

c.shape ## no_of 2-d arrays,no_of rows,no_of columns.

(2, 2, 4)

### Reshaping of arrays:

* changing the dimension of the array.


In [127]:
a = np.arange(1,9)
a.ndim

1

In [130]:
v = a.reshape(2,4)
v

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
v.ndim

2

In [132]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [134]:
a.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [135]:
a.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [136]:
a.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [137]:
a.reshape(2,4,1)

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [141]:
b  = np.arange(1,20,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

* These are all the possible ways of reshaping above 1-d array:

10,1
1,10
5,2
2,5

2,5
5,2
2,5,1
2,1,5

b.reshape(5,2)
b.reshape(10,1)
b.reshape(1,10)

5,2,1
2,1,5
2,5,1


In [143]:
b.reshape(5,2,1)

array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]],

       [[13],
        [15]],

       [[17],
        [19]]])

In [144]:
b.reshape(5,1,2)

array([[[ 1,  3]],

       [[ 5,  7]],

       [[ 9, 11]],

       [[13, 15]],

       [[17, 19]]])

In [145]:
b.reshape(10,1,1,)

array([[[ 1]],

       [[ 3]],

       [[ 5]],

       [[ 7]],

       [[ 9]],

       [[11]],

       [[13]],

       [[15]],

       [[17]],

       [[19]]])

In [146]:
b.reshape(2,-1)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [147]:
b.reshape(-1,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [148]:
b.reshape(-1,5,2)

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]]])

In [151]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])